
/* This file was generated automatically by Zephir do not modify it! */

#ifndef ZEPHIR_CLASS_ENTRIES_H
#define ZEPHIR_CLASS_ENTRIES_H

#include "zatabase/db.zep.h"
#include "zatabase/db/exception.zep.h"
#include "zatabase/di.zep.h"
#include "zatabase/di/exception.zep.h"
#include "zatabase/di/injectable.zep.h"
#include "zatabase/di/injectionawareinterface.zep.h"
#include "zatabase/di/service.zep.h"
#include "zatabase/di/service/builder.zep.h"
#include "zatabase/di/serviceinterface.zep.h"
#include "zatabase/diinterface.zep.h"
#include "zatabase/exception.zep.h"
#include "zatabase/execute.zep.h"
#include "zatabase/execute/complexresults.zep.h"
#include "zatabase/execute/condition.zep.h"
#include "zatabase/execute/condition/between.zep.h"
#include "zatabase/execute/condition/equals.zep.h"
#include "zatabase/execute/condition/exception.zep.h"
#include "zatabase/execute/condition/lessthan.zep.h"
#include "zatabase/execute/condition/like.zep.h"
#include "zatabase/execute/condition/morethan.zep.h"
#include "zatabase/execute/condition/within.zep.h"
#include "zatabase/execute/delete.zep.h"
#include "zatabase/execute/exception.zep.h"
#include "zatabase/execute/insert.zep.h"
#include "zatabase/execute/querytype.zep.h"
#include "zatabase/execute/results.zep.h"
#include "zatabase/execute/select.zep.h"
#include "zatabase/execute/update.zep.h"
#include "zatabase/helper/arraytoobject.zep.h"
#include "zatabase/helper/csv.zep.h"
#include "zatabase/helper/exception.zep.h"
#include "zatabase/helper/filehandler.zep.h"
#include "zatabase/schema.zep.h"
#include "zatabase/schema/alter.zep.h"
#include "zatabase/schema/exception.zep.h"
#include "zatabase/storage/adapter/file.zep.h"
#include "zatabase/storage/btree.zep.h"
#include "zatabase/storage/btree/node.zep.h"
#include "zatabase/storage/btree/node/element.zep.h"
#include "zatabase/storage/exception.zep.h"
#include "zatabase/table.zep.h"
#include "zatabase/table/column.zep.h"
#include "zatabase/table/exception.zep.h"
#include "zatabase/table/relation.zep.h"
#include "zatabase/table/relations/belongsto.zep.h"
#include "zatabase/table/relations/hasone.zep.h"
#include "zatabase/0__closure.zep.h"
#include "zatabase/1__closure.zep.h"
#include "zatabase/2__closure.zep.h"
#include "zatabase/3__closure.zep.h"
#include "zatabase/4__closure.zep.h"
#include "zatabase/5__closure.zep.h"

#endif